### ISSUE TITLE
Apt-Get Upgrade Fail - Concerto-Full - "Rake Failed"

### ISSUE THREAD

**Issue by Loufe** [concerto/concerto#1457]
Hi,

I've run into a critical error with our Concerto installation and was hoping someone may be able to help. I went to upgrade our server's software this evening, letting apt-get upgrade do its thing. Below is what was what was written with "redacted" being for our privacy if it wasn't obvious. Running Debian.

Unfortunately I don't understand much Ruby and couldn't find out how to run the Ruby subprocess of the upgrade with a trace so I could find or provide more information.

Does anyone have any clues as to what may have happened?

Best,

Loufe

```
Do you want to continue? [Y/n] y
Setting up concerto-full (2.3.5) ...
dbconfig-common: writing config to /etc/dbconfig-common/concerto-full.conf
dbconfig-common: flushing administrative password
Successfully installed bundler-1.15.4
1 gem installed
`/var/www` is not writable.
Bundler will use `/tmp/bundler/home/redacted' as your home directory temporarily.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 12.0.0
Using i18n 0.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.2.0
Using rack 1.6.8
Using mime-types-data 3.2016.0521
Using arel 6.0.4
Using addressable 2.3.8
Using airbrake-ruby 1.8.0
Using ansi 1.5.0
Using ast 2.3.0
Using attachable 0.0.5
Using bcrypt 3.1.11
Using thor 0.19.4
Using bundler 1.15.4
Using cancancan 2.0.0
Using coffee-script-source 1.12.2
Using execjs 2.2.2
Using multipart-post 2.0.0
Using jwt 1.5.6
Using little-plugger 1.1.4
Using multi_json 1.12.1
Using memoist 0.16.0
Using os 0.9.6
Using httpclient 2.8.3
Using hurley 0.2
Using declarative 0.0.9
Using declarative-option 0.1.0
Using uber 0.1.0
Using retriable 3.1.1
Using icalendar 2.4.1
Using hike 1.2.3
Using tilt 1.4.1
Using concerto_docsplit 0.7.5
Using htmlentities 4.3.4
Using iso8601 0.9.1
Using open_uri_redirections 0.2.1
Using encryptor 3.0.0
Using ruby-xslt 0.9.9
Using connection_pool 1.2.0
Using orm_adapter 0.5.0
Using docile 1.1.5
Using ffi 1.9.18
Using rb-fsevent 0.10.2
Using rubinius-core-api 0.0.1
Using google-analytics-turbolinks 0.0.5
Using json 2.1.0
Using kaminari-core 1.0.1
Using libv8 3.16.14.19 (x86_64-linux)
Using mysql2 0.4.9
Using nprogress-rails 0.2.0.2
Using redcarpet 3.3.4
Using ref 2.0.0
Using rmagick 2.16.0
Using rubyzip 1.1.7
Using simplecov-html 0.10.2
Using sqlite3 1.3.13
Using twitter-bootstrap-rails-confirm 1.0.6
Using i18n-js 3.0.1
Using tzinfo 1.2.3
Using nokogiri 1.8.0
Using rack-test 0.6.3
Using warden 1.2.7
Using mime-types 3.1
Using airbrake 5.8.1
Using ruby-ll 2.1.2
Using bundler-audit 0.6.0
Using coffee-script 2.4.1
Using faraday 0.9.2
Using logging 2.2.2
Using representable 3.0.4
Using sprockets 2.11.3
Using rb-inotify 0.9.10
Using rubinius-actor 0.0.2
Using uglifier 2.7.2
Using therubyracer 0.12.3
Using simplecov 0.15.0
Using activesupport 4.2.9
Using loofah 2.0.3
Using mail 2.6.6
Using oga 2.10
Using signet 0.7.3
Using sawyer 0.6.0
Using sass-listen 4.0.0
Using girl_friday 0.11.2
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.4.0
Using activemodel 4.2.9
Using clockwork 2.0.2
Using delayed_job 4.1.3
Using rails-html-sanitizer 1.0.3
Using video_info 2.5.0
Using googleauth 0.5.1
Using octokit 4.2.0
Using sass 3.5.1
Using rails-dom-testing 1.0.8
Using activejob 4.2.9
Using activerecord 4.2.9
Using google-api-client 0.10.3
Using font-awesome-sass 4.7.0
Using actionview 4.2.9
Using delayed_job_active_record 4.1.2
Using kaminari-activerecord 1.0.1
Using actionpack 4.2.9
Using kaminari-actionview 1.0.1
Using actionmailer 4.2.9
Using railties 4.2.9
Using sprockets-rails 2.3.3
Using kaminari 1.0.1
Using bootstrap-datepicker-rails 1.6.4.1
Using coffee-rails 4.2.2
Using responders 2.4.0
Using jquery-rails 4.3.1
Using jquery-timepicker-rails 1.11.10
Using public_activity 1.5.0
Using rails 4.2.9
Using sass-rails 5.0.6
Using turbolinks 2.5.3
Using devise 3.5.10
Using concerto_calendar 0.0.9
Using concerto_frontend 0.4.2
Using concerto_hardware 0.8
Using concerto_iframe 0.0.9
Using concerto_remote_video 1.2
Using concerto_simple_rss 1.1
Using concerto_weather 0.5
Bundle complete! 48 Gemfile dependencies, 129 gems now installed.
Gems in the groups postgres and development were not installed.
Bundled gems are installed into ./vendor/bundle.
`/var/www` is not writable.
Bundler will use `/tmp/bundler/home/redacted' as your home directory temporarily.
rake aborted!
Timeout::Error: execution expired
/usr/share/concerto/config/initializers/01-db_create_load_or_migrate.rb:50:in `sleep'
/usr/share/concerto/config/initializers/01-db_create_load_or_migrate.rb:50:in `block in <top (required)>'
/usr/share/concerto/config/initializers/01-db_create_load_or_migrate.rb:47:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:166:in `instrument'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `each'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `each'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
/usr/share/concerto/config/environment.rb:10:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/application.rb:328:in `require_environment!'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/railties-4.2.9/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/usr/share/concerto/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => environment
(See full trace by running task with --trace)
dpkg: error processing package concerto-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 concerto-full
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mfrederickson** [comment]
Sorry for the terseness.  There's a temp file holding up the migration at least that is what it looks like.  Scan the forums for sleep and you should find a fix.  Which is just deleting that temp file I believe.

**Comment by Loufe** [comment]
Mr. Frederickson,

You were completely right! Thanks for the help!
