### ISSUE TITLE
concerto install full error code

### ISSUE THREAD

**Issue by linhux** [concerto/concerto#1550]
I have downloadet the image http://dl.concerto-signage.org/concerto_server.img.zip
and have installed this on my cloudsystem. the system starts but there is no concerto.
So i try to install it with:
- Add Concerto repository using curl -k https://get.concerto-signage.org/add_repo.sh | sh
- Install Concerto via APT sudo apt-get install concerto-full
but after 10min i have this:

Run `rake db:migrate` to update your database then try again.
dpkg: error processing package concerto-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for systemd (232-25+deb9u1) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.36.5-2+deb9u2) ...
Errors were encountered while processing:
 concerto-full
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by zr2d2** [comment]
@linhux what is the os on your cloud instance?

**Comment by linhux** [comment]
the os is debian9

**Comment by zr2d2** [comment]
It looks like there are some broken dependencies in the package version of the install. I ran into the same problem you didI had more success installing it from source with these instructions https://github.com/concerto/concerto/wiki/Installing-Concerto-2#installing-from-source.

**Comment by linhux** [comment]
i try currently on ubuntu18.04 witz the source instruktions.
when its done and all will work i make a disktemplate and a virtualmin/cloudmintemplate

**Comment by alkex992** [comment]
> i try currently on ubuntu18.04 witz the source instruktions. when its done and all will work i make a disktemplate and a virtualmin/cloudmintemplate

Did you succed to install it from source? I'm having the same problem when trying to install the concerto-full package on Debian9

**Comment by teachers-uk-net** [comment]
# A lot of this is based on how I do things
# e.g. I tend to prefer to work as root rather than
# prefix everything with sudo
# This has been tested with Ubuntu 18.04 on AWS EC2
# Ubuntu 20.04 gave me a few headaches that make it quicker
# to use 18.04.  I have successfully installed on Debian 10
# using a very similar process to the one outlined here
# Hoping that the very clever people behind concerto
# may be working on a version that works with more
# recent releases "out of the box" (and later releases of ruby)

sudo passwd root

su -

apt update
apt upgrade

# When using Azure or AWS create appropriate 
# security rules in their portals for network traffic
# Open port 80 minimum, on other servers might
# need to be using UFW or iptables

apt install -y apache2 default-mysql-server

mysql_secure_installation

apt install -y php libapache2-mod-php php-mysql

apt-get install -y build-essential apt-transport-https libapache2-mod-passenger ruby-full ruby-dev libruby imagemagick ruby-rmagick libmagickcore-dev libmagickwand-dev libssl-dev zlib1g-dev libsqlite3-dev libpq-dev default-mysql-client ruby-mysql2 default-libmysqlclient-dev libxslt1-dev nodejs git

apt install -y libreoffice ghostscript libgs-dev gsfonts poppler-utils libcurl4-openssl-dev apache2-dev libapr1-dev libaprutil1-dev

cd /var/www
mkdir cds
cd cds
git clone https://github.com/concerto/concerto.git

useradd concerto -d /var/www/cds -g 33 -M -N
passwd concerto
cd ../
chown -R concerto:www-data cds

cd /etc/apache2/sites-available
cp 000-default.conf concertoSite.conf
# create vhosts as linked to from:
# https://github.com/concerto/concerto/wiki/Installing-Concerto-2
# path to directory in this set up on ubuntu 18.04 is likely to be:
# /var/www/cds/concerto/public
editor concertoSite.conf

# this makes it work with just the ip address as the
# default virtual host
a2ensite concertoSite
a2dissite 000-default
systemctl reload apache2

cd /var/www/cds/concerto
gem install bundler:1.17.3

# Edit Gemfile.lock to change sassc to version 2.1.0 (2.4.0 hangs on install)
editor Gemfile.lock

su concerto
cd /var/www/cds/concerto
RAILS_ENV=production bundle install --path vendor/bundle

# exit back to root
exit

cd /var/www/cds/concerto
cp concerto-init.d /etc/init.d/concerto
chmod 0755 /etc/init.d/concerto
update-rc.d concerto defaults

# Visit your site using a browser
# It might look clunky but create an account
# and get started (makes sure all backend scripts run first time)

cd /var/www/cds/concerto/config
mv database.yml database.yml.ORIG
mv database.yml.mysql database.yml
# Create databases and user(s) to use with production and testing
# Only example for one here
mysql -u root -p
mysql>CREATE DATABASE my_dev_db_name;
mysql>CREATE USER 'my_username'@'localhost' IDENTIFIED BY 'my_password';
mysql>GRANT ALL PRIVILEGES ON my_dev_db_name.* TO 'my_username'@'localhost';
mysql>FLUSH PRIVILEGES;
mysql>quit

editor database.yml

su concerto
cd /var/www/cds/concerto
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake db:seed
RAILS_ENV=production bundle exec rake assets:precompile
exit

# Gives an error when doing the config check in concerto but is because
# of the user and group used earlier on
chmod 0770 /var/www/cds/concerto
chmod 0600 /var/www/cds/concerto/log

# reboot system
shutdown -r now

**Comment by 01123581321345589144233** [comment]
ok nice i will try this

**Comment by teachers-uk-net** [comment]
> Hey @teachers-uk-net , thanks you so much, it works on Ubuntu 20.04
> One addition:
> I have to add
> `gem 'bigdecimal', '1.3.5'`
> to "Gemfile" for running db:migrate

Glad it helped; I look forward to giving it a spin on 20.04 some time.

**Comment by estracke** [comment]
Hey @teachers-uk-net, now 2024 and ubuntu 20.04 when loading page i had following error on apache2 error.log:

[ 2024-01-21 18:40:49.6449 554/7fc429f10700 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1f53b7f7. Please see earlier logs for details about the error.
App 974 stdout:
App 974 stdout:
[ 2024-01-21 18:41:43.6523 554/7fc428e0c700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/cds/concerto: An error occurred while starting up the preloader.
  Error ID: 7ccb32a7
  Error details saved to: /tmp/passenger-error-WbkRP3.html
  Message from application: No such file or directory - bundle (Errno::ENOENT)
  /var/www/cds/concerto/config/boot.rb:57:in ``'
  /var/www/cds/concerto/config/boot.rb:57:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /var/www/cds/concerto/config/setup_load_paths.rb:7:in `<top (required)>'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:267:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2024-01-21 18:41:43.6549 554/7fc429f10700 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 7ccb32a7. Please see earlier logs for details about the error.


can u help me?

**Comment by virrim** [comment]
For anyone still finding their way here, it is still possible to get running on Ubuntu 20.04 by installing Ruby 2.6 through rvm.
Install RVM https://rvm.io/rvm/install
Install Ruby 2.6 (rvm install ruby 2.6) and enable it
Install Passenger through Gem (gem install passenger)
Run passenger-install-apache2-module and follow the directions at the end, except the first line will go in your passenger.load and the following four config lines will go in the passenger.conf.

Otherwise follow the guide above.
