### ISSUE TITLE
Ruby 2.7 support

### ISSUE THREAD

**Issue by prunkdump** [concerto/concerto#1577]
Hello !

I upgraded my webserver to Debian Bullseye that is only shipped with Ruby 2.7. 

Actually I can't manage to get Concerto working anymore.

I have successfully bundled it adding the fallowing line in Gemfile
`gem 'bigdecimal', '~>1.4.4'`

But an error appear when running in production :

```
  Message from application: superclass mismatch for class Mark (TypeError)
  /usr/lib/ruby/2.7.0/psych/parser.rb:34:in `<class:Parser>'
  /usr/lib/ruby/2.7.0/psych/parser.rb:33:in `<module:Psych>'
  /usr/lib/ruby/2.7.0/psych/parser.rb:2:in `<top (required)>'
  /usr/lib/ruby/2.7.0/psych.rb:20:in `require'
  /usr/lib/ruby/2.7.0/psych.rb:20:in `<top (required)>'
  /usr/lib/ruby/2.7.0/yaml.rb:4:in `require'
  /usr/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/application.rb:2:in `require'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/application.rb:2:in `<top (required)>'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails.rb:11:in `require'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails.rb:11:in `<top (required)>'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/all.rb:1:in `require'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/all.rb:1:in `<top (required)>'
  /usr/share/concerto/config/application.rb:3:in `require'
  /usr/share/concerto/config/application.rb:3:in `<top (required)>'
  /usr/share/concerto/config/environment.rb:2:in `require'
  /usr/share/concerto/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
  /usr/share/concerto/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

```
Does someone manage to get Concerto working with ruby2.7 or with Debian Bullseye and Apache passenger ?

Regards,

Baptiste.

**Comment by zr2d2** [comment]
Hi  Baptiste ,

If I'm reading this compatibility table
<https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html>
right, we'll need to upgrade to rail 6 in order to use ruby 2.7. I started
a branch to upgrade to rails 5 here
<https://github.com/concerto/concerto/blob/rails5/Gemfile>, if you'd
like to contribute to it. I think that will be the first step

Zach Rowe
